export type AppIconName =
  | 'add'
  | 'alert'
  | 'arrow-left'
  | 'check'
  | 'clone'
  | 'close'
  | 'delete'
  | 'edit'
  | 'environment'
  | 'eye'
  | 'eye-off'
  | 'knowledge'
  | 'members'
  | 'moon'
  | 'refresh'
  | 'repository'
  | 'save'
  | 'search'
  | 'settings'
  | 'shield-check'
  | 'status'
  | 'sun'
  | 'versions'

export type AppButtonVariant =
  | 'primary'
  | 'secondary'
  | 'danger'
  | 'danger-outline'
  | 'text'
  | 'text-danger'
  | 'plain'

export type AppControlSize = 'sm' | 'md' | 'lg'
