export type AppIconName =
  | 'add'
  | 'alert'
  | 'arrow-left'
  | 'check'
  | 'close'
  | 'delete'
  | 'edit'
  | 'environment'
  | 'eye'
  | 'eye-off'
  | 'knowledge'
  | 'members'
  | 'refresh'
  | 'repository'
  | 'save'
  | 'search'
  | 'settings'
  | 'shield-check'
  | 'status'
  | 'versions'

export type AppButtonVariant =
  | 'primary'
  | 'secondary'
  | 'danger'
  | 'danger-outline'
  | 'text'
  | 'text-danger'
  | 'plain'
